#pretrained_model = '/home/dzm44/Documents/projects/clinical-bert/clinical-bert-weights'
#code_graph_file = '/home/dzm44/Documents/data/icd_codes/code_graph_radiology_expanded.pkl'
path_to_clinical_bert_repo = '/content/clinicalBERT'
pretrained_model = '/content/ClinicalBERT_checkpoint/ClinicalBERT_discharge_pytorch_checkpoint'
code_graph_file = '/content/preprocessing-ehr/icd_codes/code_graph_radiology_expanded.pkl'
#data_dir = '/home/dzm44/Documents/data/Dataset_10-11-2019/preprocessed/reports_and_codes_expanded'
data_dir = '/content/mimic_synthetic_data_100-assembled'
#data_dir = '/home/jered/Documents/data/Dataset_10-11-2019/preprocessed/mini'
#data_dir = '/home/jered/Documents/data/mimic-iii-clinical-database-1.4/preprocessed/reports_and_codes_expanded'
#data_dir = '/home/jered/Documents/data/mimic-iii-clinical-database-1.4/preprocessed/mini'
val_file = 'val.data'
#val_file = 'test.data'

# training params
learning_rate_unfrozen = .00001
learning_rate_frozen = .001
batch_size = 4
epochs = 1
#epochs = 5
limit_rows_train = 10000
#limit_rows_train = None
limit_rows_val = 1000
#limit_rows_val = None
subbatches = 8
num_workers = 0
checkpoint_every = 10
copy_checkpoint_every = 300
val_every = 10
email_every = 30
expensive_val_every = 500
#expensive_val_every = None

#  model params
sentences_per_checkpoint = 30
concatenate_code_embedding = True

# email params
smtp_server = 'smtp.gmail.com'
port = 465
sender_email = 'pravin.s.shetty@gmail.com'
receiver_email = 'pravin.s.shetty@gmail.com'
